version: 0.2
phases: 
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      # Run test
      - echo Starting Pre Build phase......
      - pip install -r requirements.txt
      - python manage.py test
  build: 
    commands:
      # build and push docker image to ECR
      - echo Starting the Build Stage.......
      - export IMAGE_NAME=awstest-demo
      - export REPOSITORY_URI=490004626891.dkr.ecr.us-east-1.amazonaws.com/awstest-demo
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Building Image......
      - docker build -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Build Complete......
  post_build:
    commands:
      - echo Starting Post Build Stage......
      - export DOCKER_CONTAINER_NAME=awstest-demo
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Generated imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json